direction: right

classes: {
    coreclass: {
            width: 200
               style: {
                     stroke-width: 0
                    fill: "#44C7B1"
                    shadow: true
                    border-radius: 5
               }
      }
    propclass: {
            width: 200
               style: {
                     stroke-width: 0
                     fill: honeydew
                    shadow: true
                    border-radius: 5
               }
      }
}

*.class: coreclass
p.class: propclass
rs.class: propclass

p: providers {
    obis
    emodnet
    bcodmo
    wod
    cchdo
    *.class: coreclass

}

s: Summoned Set

rs: Reasoning Set {
    f: frames
    sh: SHACL AF
    voc: Vocabulary of Instances
    gc: Graph generating\n analysis (ex: OBIS)
    *.class: coreclass

}

rt: Reasoned Triples
dg: DOOS Graph {
note: |md
Has a known set of triples by type and property for products and facets workflow.
|
}

p -> s: gleaner et al
rs -> rt: via pyld and pyshacl

rt -> dg
s -> dg

