# mkdocs.yml
site_name: Earthcube Utilities
theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [earthcube_utilities/src, summarize/src ]
nav:
    - Summarize: summarize/
    - Notebook Proxy: notebook_proxy/README.md
    - Earthcube Utilities: earthcube_utilities/index.md
    - Code Reference:
        - Earthcube Utilites: earthcube_utilities/earthcube_utilities_code.md
        - Summarize: summarize/summarize_code.md