# mkdocs.yml
site_name: Earthcube Utilities
theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [earthcube_utilities/src, summarize/src ]
nav:
    - Summarize: ./summarize/README.md
    - Notebook Proxy: ./notebook_proxy/README.md
    - Earthcube Utilities: ./earthcube_utilities/docs/index.md
    - Code Reference:
        - Earthcube Utilites: earthcube_utilities.md
        - Summarize: summarize.md