# mkdocs.yml
site_name: Earthcube Utilities
theme:
  name: "material"
  features:
#    - content.code.copy
    - navigation.sections
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
     custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [earthcube_utilities/src, summarize/src ]
- mermaid2
#- literate-nav
#https://pypi.org/project/mkdocs-jupyter/
- mkdocs-jupyter
- callouts
- include-markdown

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
    - Summarize: summarize/
    - Notebook Proxy: notebook_proxy/README.md
    - Earthcube Utilities:
        - Documentation: earthcube_utilities/index.md
        - Scripts: earthcube_utilities/earthcube_utilities_scripts.md
    - Code Reference:
        - Earthcube Utilites: earthcube_utilities/earthcube_utilities_code.md
        - Summarize: summarize/summarize_code.md