prefix schema: <https://schema.org/>

# Distribution Properties by Popularity
# Counts which distribution properties are most commonly used across all providers
# Based on: https://github.com/earthcubearchitecture-project418/assay-data/blob/master/README.md#dataset-distribution
SELECT DISTINCT ?p (COUNT(DISTINCT ?g) as ?num_providers)
WHERE { 
  GRAPH ?g {
    ?dataset a schema:Dataset .
    ?dataset schema:distribution ?distro .
    ?distro ?p ?o .
    FILTER NOT EXISTS { ?distro <https://www.w3.org/2000/01/rdf-schema#seeAlso> ?o }
  }
} 
GROUP BY ?p
ORDER BY DESC(?num_providers)


