SELECT ?repo (COUNT(distinct ?g) as ?graphs) (COUNT(*) as ?triples)
WHERE {
  GRAPH ?g {
      ?s ?p ?o .
       bind(  REPLACE(REPLACE( STR(?g) ,"urn:(?:\\w+):" ,"" ), ":\\w+$$" , "")   as ?repo )
       FILTER( CONTAINS(str(?g), ":${repo}:") )
   }
}
group by ?repo