# Based on: https://github.com/multirepo-docs/root-docs:

name: mkdocs
on:
  push:
    branches:
      - main
      - dev
      - docs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-mermaid2-plugin
#      - run: pip install mkdocs-schema-reader
      - run: pip install mkdocs-multirepo-plugin
      - run: pip install mkdocs-literate-nav
      - run: pip install mkdocs-jupyter
      - run: pip install mkdocs-callouts
      - run: pip install mkdocstrings-python
      - name: Checkout
        uses: actions/checkout@v3
## no cleaup needed
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          repository: earthcube/geocodes
#          path: docs/geocodes
#      - run: cd docs/geocodes && rm -rf '!(docs)' && cd ..
#
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          repository: earthcube/GeoCODES-Metadata
#          path: docs/GeoCODES-Metadata
#      - run: cd docs/GeoCODES-Metadata && rm -rf archive && cd ..
##      - run: cd docs/GeoCODES-Metadata && rm -rf '!(docs)' && cd ..
#
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          repository: gleanerio/gleaner
#          path: docs/gleaner
#      - run: cd docs/gleaner && rm -rf '!(docs)' && cd ..
#
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          repository: gleanerio/nabu
#          path: docs/nabu
#      - run: cd docs/nabu && rm -rf '!(docs)' && cd ..


 #     - run: cd docs/ && mkdocs gh-deploy --force --clean --verbose

### note ######################
      # might copy the top level readme.md from a package to docs/index.html
      # so that mkdocs can utilize the information
      # or see if https://github.com/mondeja/mkdocs-include-markdown-plugin works the mkdocs-multirepo-plugin
### ######################


# COPY DOCS
      - run: cd summarize/docs; cp -r *  ../../docs/summarize/
      -  run: cp -r summarize/README.md  docs/summarize/index.md
      - run: cd  earthcube_utilities/docs; cp -r *  ../../docs/earthcube_utilities/
      -  run: cp -r earthcube_utilities/README.md  docs/earthcube_utilities/README.md
      -  run: cp -r notebook_proxy/README.md  docs/notebook_proxy/README.md
 # BUILD DOCS
      - run:  mkdocs gh-deploy  --force --clean --verbose

        # old one
#      - run:  cd earthcube_utilities &&  mkdocs gh-deploy --force --clean --verbose
 #     - run:  cd summarize &&  mkdocs gh-deploy  --dirty --verbose
 #     - run:  cd notebook_proxy &&  mkdocs gh-deploy  --verbose --site-dir notebook_proxy
